---
# Ansible Galaxy Requirements
# ===========================
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Windows module collection (required for win_shell, win_stat, etc.)
  - name: ansible.windows
    version: ">=1.13.0"

  # General community modules (required for mail module)
  - name: community.general
    version: ">=6.0.0"
