---
- name: Backup and maintain Tableau
  hosts: TSMPrimary
  gather_facts: yes

  tasks:

  - name: Logging into TSM...
    raw: tsm login -s localhost -u TSM_USERNAME -p TSM_PASSWORD

  - name: Getting backup folder locations from tsm configuration...
    raw: tsm configuration get -k basefilepath.backuprestore
    register: result_2_backup_folder

  - name: Getting log archive folder location from tsm configuration...
    raw: tsm configuration get -k basefilepath.log_archive
    register: result_3_logs_folder

  - name: Exporting ServerSettings.json file...
    raw: "tsm settings export -f {{ result_2_backup_folder.stdout_lines[0] }}/ServerSettings{{ ansible_date_time.iso8601_basic_short }}.json"
    register: result_4_settings

  - name: Run tsm maintenance ziplogs...
    raw: tsm maintenance ziplogs -a -f logs_{{ ansible_date_time.iso8601_basic_short }}.zip
    register: result_5_ziplogs

  - name: Running tsm maintenance cleanup...
    raw: tsm maintenance cleanup -l -t -r -q
    register: result_6_cleanup

  - name: Running tsm Maintenance backup...
    raw: tsm maintenance backup -f ts_backup{{ansible_date_time.iso8601_basic_short }}
    register: result_7_backup

  - name: Deleting .tsbak files older than 4 days...
    win_shell: Get-ChildItem –Path {{ result_2_backup_folder.stdout_lines[0] }} -Recurse
               | Where-Object {($_.LastWriteTime -lt (Get-Date).AddDays(-4))}
               | Remove-Item -Recurse

  - name: Deleting zip logs older than 4 days...
    win_shell: Get-ChildItem –Path {{ result_3_logs_folder.stdoutlines[0] }} -Recurse
               | Where-Object {($_.LastWriteTime -lt (Get-Date).AddDays(-4))}
               | Remove-Item -Recurse

  - name: Listing contents of backup folder...
    win_shell: dir
    args:
      chdir: "{{ result_2_backup_folder.stdout_lines[0] }}"
    register: result_8_listbackups

  - name: Listing contents of logs folder...
    win_shell: dir
    args:
      chdir: "{{ result_3_logs_folder.stdoutlines[0] }}"
    register: result_9_listlogs

  - name: Sending E-Mail on end of installation...
    mail:
      host: smtpserver.com
      subject: ANSIBLE | Tableau - Backup has completed at {{ ansible_date_time.iso8601_basic_short }}
      subtype: html
      body: '
<h1>Tableau Backup has completed on {{ ansible_hostname }} at {{  ansible_date_time.iso8601_basic_short  }}</h1>
<p>*****RESULTS OF ServerSettings.json*****<br><br>{{ result_4_settings.stdout }}</p>
<p>*****RESULTS OF tsm maintenance ziplogs*****<br><br>{{ result_5_ziplogs.stdout }}</p>
<p>*****RESULTS OF tsm maintenance cleanup*****<br><br>{{ result_6_cleanup.stdout }}</p>
<p>*****RESULTS OF tsm maintenance backup*****<br><br>{{ result_7_backup.stdout }}</p>
<p>*****Contents of {{ result_2_backup_folder.stdout_lines[0] }}<br><br>{{ result_8_listbackups.stdout_lines }}*****</p>
<p>*****Contents of {{ result_3_logs_folder.stdout_lines[0] }}<br><br>{{ result_9_listlogs.stdout_lines }} *****</p>
'
      from: email@gmail.com
      to:
      - Mike <mike@gmail.com>
      - Mark <mark@gmail.com>
    delegate_to: localhost
    ignore_errors: true
